spring:
  datasource:
    url: jdbc:mysql://localhost:3307/kc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
